#pragma once

//put things we want for whole project here
#include <iostream>
using namespace std;

enum POWER_UP_TYPE
{
	SPIT_FREQUENCY,
	SPEED_UP
};

enum PLAYER_ANIMATION
{
	PLAYER_ANIM_STATIONARY,
	PLAYER_ANIM_WALKING1,
	PLAYER_ANIM_WALKING2,
	PLAYER_ANIM_SPITTING1,
	PLAYER_ANIM_SPITTING2,
	PLAYER_ANIM_SPITTING3
};

enum PLAYER_STATUS
{
	PLAYER_MOVING,
	PLAYER_STATIONARY,
	PLAYER_SPITTING
};

enum MONSTER_TYPE
{
	SLUG,
	MOTH,
	FAT_WALKER
};

enum GAME_LOOP_STATE
{
	WAVE_BEGIN,
	WAVE_RUNNING,
	WAVE_END,	
};

enum TERRAIN_DIRECTION
{
	TERRAIN_DIRECTION_RIGHT,
	TERRAIN_DIRECTION_UP
};

enum FOUR_WAY_ROTATION
{
	ROT_0,
	ROT_90,
	ROT_180,
	ROT_270
};

enum RIVER_TILE_TYPE
{
	STRAIGHT,
	CORNER
};

enum MONSTER_STATE
{
	MOVING,
	CHARGING,
	PAUSED
};

enum MOTH_ANIMATION
{
	MOTH_ANIM_MOVE1,
	MOTH_ANIM_MOVE2,
	MOTH_ANIM_MOVE3,
	MOTH_ANIM_MOVE4,
	MOTH_ANIM_HIT,
};

enum FAT_WALKER_ANIMATION
{
	WALKER_ANIM_STATIONARY,
	WALKER_ANIM_MOVEMENT1,
	WALKER_ANIM_MOVEMENT2,
	WALKER_ANIM_HIT,
};

enum SLUG_ANIMATION
{
	SLUG_ANIM_STATIONARY,
	SLUG_ANIM_MOVEMENT1,
	SLUG_ANIM_MOVEMENT2,
	SLUG_ANIM_HIT,
};

enum EXPLOSION_ANIMATION
{
	EXP_ANIM_1,
	EXP_ANIM_2,
	EXP_ANIM_3,
	EXP_ANIM_4,
};

enum HIT_ANIMATION
{
	HIT_ANIM_1,
	HIT_ANIM_2
};

#define SCREEN_W 1680
#define SCREEN_H 1050

#define PLAYER_W 64
#define PLAYER_H 64

#define PLAYER_SPEED 230.0

#define TERRAIN_COLS 16
#define TERRAIN_ROWS 16
#define TERRAIN_W 128
#define TERRAIN_H 128

#define BATTLE_FIELD_W TERRAIN_W * TERRAIN_COLS
#define BATTLE_FIELD_H TERRAIN_H * TERRAIN_ROWS

#define FENCE_TILE 32
#define TERRAIN_TILE_OVER_FENCE_TILE TERRAIN_H / FENCE_TILE
#define BORDER_FENCE_TILES TERRAIN_TILE_OVER_FENCE_TILE * (TERRAIN_COLS - 1)


#define LOOGIE_RELOAD 0.6
#define LOOGIE_W 16
#define LOOGIE_H 16
#define LOOGIE_VELOCITY 750.0
#define SPIT_POOL 20

#define POWER_UP_W 64
#define POWER_UP_H 64

#define SAFE_SPAWN_DISTANCE 500.0

#define PI 3.14159

#define MOTH_MAX_SPEED 200
#define MOTH_ACCEL 250

#define PLAYER_U_MIN 0
#define PLAYER_V_MIN 0.80
#define PLAYER_U_STEP 0.125
#define PLAYER_V_STEP 0.2

#define MOTH_U_MIN 0
#define MOTH_V_MIN 0.6
#define MOTH_U_STEP 0.125
#define MOTH_V_STEP 0.2

#define WALKER_U_MIN 0
#define WALKER_V_MIN 0.4
#define WALKER_U_STEP 0.125
#define WALKER_V_STEP 0.2

#define SLUG_U_MIN 0
#define SLUG_V_MIN 0.2
#define SLUG_U_STEP 0.125
#define SLUG_V_STEP 0.2



#define EXPLOSION_U_MIN 0
#define EXPLOSION_V_MIN 0
#define EXPLOSION_U_STEP 0.25
#define EXPLOSION_V_STEP 1

#define HIT_U_MIN 0
#define HIT_V_MIN 0
#define HIT_U_STEP 0.5
#define HIT_V_STEP 1


